name: github-action-email
on: [push]
jobs:
  log-github-event-goodies:
    name: "log message"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: echo "${{ github.event.head_commit.message }}"
